# Generated by Django 3.2.6 on 2021-11-12 00:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostNFound',
            fields=[
                ('reg_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('stud_num', models.CharField(max_length=11, verbose_name='Student Number')),
                ('email', models.EmailField(blank=True, max_length=50, unique=True, verbose_name='Email')),
                ('contact', models.CharField(max_length=11, verbose_name='Contact Number')),
                ('found', models.BooleanField(default=False, verbose_name='Found?')),
                ('lost', models.BooleanField(default=False, verbose_name='Lost?')),
                ('item', models.CharField(max_length=100, verbose_name='Item')),
                ('item_desc', models.TextField(max_length=500, verbose_name='Item Description')),
                ('pick_up_loc', models.CharField(default='SAO office', max_length=100, verbose_name='Pick-up Location')),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='User Name')),
                ('gender', models.CharField(max_length=50, verbose_name='Gender')),
                ('user_text', models.TextField(null=True, verbose_name='User Input')),
                ('user_session', models.CharField(max_length=150, null=True, verbose_name='User Session')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('visits', models.IntegerField(null=True, verbose_name='Number of visit')),
            ],
            options={
                'db_table': 'user_session',
            },
        ),
    ]
